web: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --max-requests 500 --max-requests-jitter 50
worker: celery -A backend worker --loglevel=info --concurrency=1 --max-tasks-per-child=100

