# Generated by Django 4.2.7 on 2025-07-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_alter_user_age_alter_user_gender_alter_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
