# Generated by Django 4.2.7 on 2025-08-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('newsletter_welcome', 'Newsletter Welcome'), ('waitlist_confirmation', 'Waitlist Confirmation'), ('generic', 'Generic Email')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
