# Generated by Django 4.2.7 on 2026-02-04 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0003_user_availability_status_user_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BondcoinWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Visibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="usermatch",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="bondmakersubscription",
            name="start_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userroleselection",
            name="selected_role",
            field=models.CharField(
                choices=[
                    ("looking_for_love", "Looking for Love"),
                    ("bondmaker", "Bondmaker"),
                ],
                default="looking_for_love",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="usermatch",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_user_match"
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="bondmaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visible_to_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibility_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bondcoinwallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bondcoin_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visibility",
            unique_together={("owner", "bondmaker")},
        ),
    ]
