# Generated by Django 4.2.7 on 2026-02-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0005_alter_usermatch_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermatch",
            unique_together=set(),
        ),
    ]
