# Generated by Django 4.2.7 on 2025-08-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_adminuser_job_benefits_job_responsibilities_adminotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('character_count', models.PositiveIntegerField()),
                ('translation_time', models.FloatField(help_text='Translation time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
