# Generated by Django 4.2.7 on 2026-02-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0008_revenuerecord_matchrevenuesplit_matchrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondcoinpackage",
            name="apple_product_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="bondcoinpackage",
            name="google_product_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
