# Generated by Django 4.2.7 on 2026-02-10 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0011_alter_emailverification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="registration_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="temp_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
