# Generated by Django 4.2.7 on 2026-02-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0013_usermatch_match_request_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="kids_plans",
            new_name="future_kids",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="kids_preference",
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="reset_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deal_breaker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="genotype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AA", "AA"),
                    ("AS", "AS"),
                    ("SS", "SS"),
                    ("AC", "AC"),
                    ("SC", "SC"),
                    ("PNTS", "Prefer not to say"),
                ],
                help_text="User's genotype (optional)",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="have_kids",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="no_of_kids",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="partner_qualities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="traits",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("trans_man", "Trans Man"),
                    ("trans_woman", "Trans Womman"),
                    ("non_binary", "Non Binary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of general interests",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("engaged", "Engaged"),
                    ("married", "Married"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="religion_importance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very", "Very Important"),
                    ("somewhat", "Somewhat Important"),
                    ("not_at_all", "Not At All"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("harassment", "Harassment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dating.usermatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("reporter", "reported_user", "user_match")},
            },
        ),
    ]
