# Generated by Django 4.2.7 on 2026-02-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0014_rename_kids_plans_user_future_kids_remove_user_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="future_kids",
            new_name="kids_plans",
        ),
    ]
