# Generated by Django 4.2.7 on 2025-10-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0017_bondcoinpackage_bondcointransaction_giftcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tip_amount',
            field=models.PositiveIntegerField(default=0, help_text='Tip amount in Bondcoins'),
        ),
        migrations.AddField(
            model_name='message',
            name='tip_gift',
            field=models.ForeignKey(blank=True, help_text='Gift sent with this message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dating.virtualgift'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice_note', 'Voice Note'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('system', 'System Message'), ('matchmaker_intro', 'Matchmaker Introduction'), ('call_start', 'Call Started'), ('call_end', 'Call Ended'), ('tip', 'Tip Message')], default='text', max_length=20),
        ),
    ]
