# Generated by Django 4.2.7 on 2026-02-12 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0018_merge_20260212_0926"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="reset_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, blank=True
            ),
        ),
    ]
