# Generated by Django 4.2.7 on 2026-02-12 10:05

from django.db import migrations, models
import uuid
from django.db import connection


def add_reset_token_field_if_not_exists(apps, schema_editor):
    table_name = "dating_passwordresetotp"
    column_name = "reset_token"

    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = '{table_name}'
              AND column_name = '{column_name}';
            """
        )
        exists = cursor.fetchone()

    if not exists:
        # Get the model
        PasswordResetOTP = apps.get_model("dating", "PasswordResetOTP")
        field = models.UUIDField(
            default=uuid.uuid4, editable=False, null=True, blank=True
        )
        schema_editor.add_field(PasswordResetOTP, field)


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0018_merge_20260212_0926"),
    ]

    operations = [
        migrations.RunPython(
            add_reset_token_field_if_not_exists, reverse_code=migrations.RunPython.noop
        ),
    ]
