# Generated by Django 4.2.7 on 2026-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0019_add_reset_token_to_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="otp_code",
            field=models.CharField(max_length=6),
        ),
    ]
