# Generated by Django 4.2.7 on 2026-02-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0019_add_reset_token_to_passwordresetotp"),
        ("dating", "0020_alter_emailverification_otp_code"),
    ]

    operations = []
