# Generated by Django 4.2.7 on 2026-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0022_merge_20260212_1927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersecurityquestion",
            name="response",
        ),
        migrations.AddField(
            model_name="usersecurityquestion",
            name="response_choice",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usersecurityquestion",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usersecurityquestion",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersecurityquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("data_protection", "How will you protect user data?"),
                    (
                        "scam_prevention",
                        "What actions will you take if you suspect a scam or fake profile?",
                    ),
                    (
                        "relationship_guidance",
                        "Do you also provide relationship guidance?",
                    ),
                    (
                        "matchmaking_evolution",
                        "How do you see matchmaking evolving in the 21st century?",
                    ),
                    ("unique_skills", "What unique skills set you apart?"),
                    (
                        "business_service",
                        "Do you run matchmaking as a business or community service?",
                    ),
                    ("user_verification", "How do you verify users are real people?"),
                ],
                max_length=50,
            ),
        ),
    ]
