# Generated by Django 4.2.7 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0023_remove_usersecurityquestion_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchrequest",
            name="bondmaker_earning",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="matchrequest",
            name="platform_revenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
