# Generated by Django 4.2.7 on 2026-02-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0026_alter_user_dating_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
