# Generated by Django 4.2.7 on 2026-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0028_visibility_status_delete_cointransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("casual", "Casual Dating"),
                            ("lgbtq", "LGBTQ+"),
                            ("lavender", "Lavender Marriage"),
                            ("sugar", "Sugar Relationship"),
                            ("marriage", "Marriage-Oriented"),
                            ("companionship", "Companionship"),
                            ("cultural", "Cultural Matching"),
                            ("elite", "Elite Only Matching"),
                            ("widow", "Widow/Widower Matchmaking"),
                            ("divorced", "Divorced/Single Parent Matching"),
                            ("career", "Career Focused Matching"),
                            ("arabs", "Arabs/Khaṭṭābah Matching"),
                            ("hindi", "Hindi/Punjabi Matching"),
                            ("christian", "Christian Matching"),
                            ("islam", "Islam Matching"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="matchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="matchrequest",
            index=models.Index(
                fields=["bondmaker", "status"], name="dating_matc_bondmak_799909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrequest",
            index=models.Index(fields=["status"], name="dating_matc_status_cfac84_idx"),
        ),
        migrations.AddField(
            model_name="user",
            name="specialisations",
            field=models.ManyToManyField(
                blank=True, related_name="bondmakers", to="dating.specialisation"
            ),
        ),
    ]
