# Generated by Django 4.2.7 on 2026-02-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0029_specialisation_alter_matchrequest_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BondmakerTaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateField()),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visibility",
            index=models.Index(
                fields=["bondmaker", "status", "visibility"],
                name="dating_visi_bondmak_23127b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visibility",
            index=models.Index(
                fields=["expires_at"], name="dating_visi_expires_dd08f3_idx"
            ),
        ),
        migrations.AddField(
            model_name="bondmakertaskcompletion",
            name="bondmaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bondmakertaskcompletion",
            index=models.Index(
                fields=["bondmaker", "completed_at"],
                name="dating_bond_bondmak_ca41b2_idx",
            ),
        ),
    ]
