# Generated by Django 4.2.7 on 2026-02-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0032_bondcircle_bondcirclepost_alter_visibility_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("share", "Share")], max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="storyreaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storyreaction",
            name="story",
        ),
        migrations.RemoveField(
            model_name="storyreaction",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="postinteraction",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="postinteraction",
            name="dating_post_user_id_6d7aa3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="bondcirclemember",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="story",
            name="reactions_count",
        ),
        migrations.RemoveField(
            model_name="story",
            name="views_count",
        ),
        migrations.AddField(
            model_name="chat",
            name="user_match",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat",
                to="dating.usermatch",
            ),
        ),
        migrations.AlterField(
            model_name="bondmakersubscription",
            name="bondmaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bondmakersubscription",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bondmakersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("bond", "Bond"),
                    ("share", "Share"),
                    ("save", "Save"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="bondmakersubscription",
            index=models.Index(
                fields=["bondmaker", "active"], name="dating_bond_bondmak_5920d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bondmakersubscription",
            index=models.Index(
                fields=["user", "active"], name="dating_bond_user_id_843fc4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bondcirclemember",
            constraint=models.UniqueConstraint(
                fields=("circle", "user"), name="unique_user_per_circle"
            ),
        ),
        migrations.DeleteModel(
            name="StoryReaction",
        ),
        migrations.AddField(
            model_name="storyinteraction",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="dating.story",
            ),
        ),
        migrations.AddField(
            model_name="storyinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storyinteraction",
            unique_together={("user", "story", "interaction_type")},
        ),
    ]
