# Generated by Django 5.2.11 on 2026-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0036_adminrole_user_created_by_user_is_principal_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("support", "Support"),
                    ("moderator", "Moderator"),
                    ("finance", "Finance"),
                    ("manager", "Manager"),
                    ("viewer", "Viewer"),
                    ("super_admin", "Super_admin"),
                    ("admin", "Admin"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
