# Generated by Django 5.2.11 on 2026-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0037_alter_adminrole_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
