# Generated by Django 5.2.11 on 2026-04-03 20:47

from django.db import migrations


def create_specialisations(apps, schema_editor):
    Specialisation = apps.get_model("dating", "Specialisation")

    categories = [
        "casual",
        "lgbtq",
        "lavender",
        "sugar",
        "marriage",
        "companionship",
        "cultural",
        "elite",
        "widow",
        "divorced",
        "career",
        "arabs",
        "hindi",
        "christian",
        "islam",
    ]

    for category in categories:
        Specialisation.objects.get_or_create(category=category)


def reverse_specialisations(apps, schema_editor):
    Specialisation = apps.get_model("dating", "Specialisation")

    categories = [
        "casual", "lgbtq", "lavender", "sugar", "marriage",
        "companionship", "cultural", "elite", "widow",
        "divorced", "career", "arabs", "hindi",
        "christian", "islam",
    ]

    Specialisation.objects.filter(category__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0040_alter_deviceregistration_unique_together"),
    ]

    operations = [
        migrations.RunPython(create_specialisations, reverse_specialisations),
    ]
