# Generated by Django 5.2.11 on 2026-04-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0046_remove_post_bonds_count_remove_post_shares_count"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="dating_post_post_ty_80be04_idx",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_type",
        ),
    ]
