# Generated by Django 5.2.11 on 2026-04-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0048_documentverification_experience_years"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersocialhandle",
            name="handle",
        ),
    ]
