# Generated by Django 5.2.11 on 2026-04-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0049_remove_usersocialhandle_handle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentverification",
            name="experience_years",
        ),
    ]
