# Generated by Django 5.2.11 on 2026-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0051_deviceregistration_token_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminpermission",
            name="can_approve_applications",
            field=models.BooleanField(default=False),
        ),
    ]
