# Generated by Django 5.2.11 on 2026-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0054_message_deleted_for_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("asian", "Asian"),
                    ("hispanic", "Hispanic"),
                    ("middle_eastern", "Middle Eastern"),
                    ("mixed", "Mixed"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="want_kids",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe")],
                max_length=20,
                null=True,
            ),
        ),
    ]
