# Generated by Django 5.2.11 on 2026-06-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0055_user_ethnicity_user_want_kids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_bondmaker_update",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_like",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_new_match",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_promotional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="thought_leadership",
            field=models.TextField(blank=True, null=True),
        ),
    ]
