# Generated by Django 5.2.11 on 2026-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0056_user_notify_on_bondmaker_update_user_notify_on_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cumulative_successful_matches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="current_cached_badge_tier",
            field=models.CharField(default="Uprising", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="current_cached_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_level_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
