# Generated by Django 5.2.11 on 2026-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0057_user_cumulative_successful_matches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermatch",
            name="progression_processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
