# Generated by Django 5.2.11 on 2026-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0059_passwordresetotp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
