# Generated by Django 5.2.11 on 2026-10-02 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0061_securitypin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDeviceCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('last_synced_seq', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='last_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_delivered_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_read_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='change_seq',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='seq',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'change_seq'], name='dating_mess_chat_id_19b342_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('chat', 'seq'), name='unique_message_seq_per_chat'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='unique_client_message_id_per_sender'),
        ),
        migrations.AddField(
            model_name='chatdevicecursor',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_cursors', to='dating.chat'),
        ),
        migrations.AddField(
            model_name='chatdevicecursor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_device_cursors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatdevicecursor',
            constraint=models.UniqueConstraint(fields=('chat', 'user', 'device_id'), name='unique_chat_device_cursor'),
        ),
    ]
