from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from datetime import date

User = get_user_model()

TEST_PASSWORD = "Bondah@2025"

SEEKERS = [
    {
        "email": "amara.osei@bondah.test",
        "name": "Amara Osei",
        "username": "amara_osei",
        "gender": "female",
        "date_of_birth": date(1995, 4, 12),
        "city": "Accra",
        "state": "Greater Accra",
        "country": "Ghana",
        "bio": "Travel enthusiast and foodie. Looking for someone who loves adventures as much as I do.",
        "looking_for": "A kind, ambitious man who values family and isn't afraid to be vulnerable.",
        "religion": "Christian",
        "religion_importance": "somewhat",
        "genotype": "AA",
        "ethnicity": "black",
        "education_level": "bachelor",
        "job_title": "Marketing Manager",
        "company_name": "Unilever Ghana",
        "have_kids": "no",
        "want_kids": "yes",
        "future_kids": "yes",
        "marriage_plans": "yes",
        "relationship_status": "single",
        "dating_type": "serious",
        "open_to_long_distance": "maybe",
        "personality_type": "ENFJ",
        "love_language": "quality_time",
        "communication_style": "direct",
        "smoking_preference": "never",
        "drinking_preference": "occasionally",
        "pet_preference": "dog",
        "exercise_frequency": "3x_week",
        "hobbies": ["hiking", "cooking", "photography"],
        "interests": ["travel", "music", "art"],
        "preferred_gender": "male",
        "age_range_min": 28,
        "age_range_max": 42,
        "max_distance": 100,
        "profile_picture": "https://randomuser.me/api/portraits/women/44.jpg",
    },
    {
        "email": "kofi.mensah@bondah.test",
        "name": "Kofi Mensah",
        "username": "kofi_mensah",
        "gender": "male",
        "date_of_birth": date(1991, 8, 23),
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "bio": "Software engineer by day, chef by night. I believe good food brings people together.",
        "looking_for": "A woman who is driven, has a great sense of humour, and loves trying new restaurants.",
        "religion": "Christian",
        "religion_importance": "somewhat",
        "genotype": "AS",
        "ethnicity": "black",
        "education_level": "master",
        "job_title": "Senior Software Engineer",
        "company_name": "Andela",
        "have_kids": "no",
        "want_kids": "yes",
        "future_kids": "yes",
        "marriage_plans": "yes",
        "relationship_status": "single",
        "dating_type": "marriage",
        "open_to_long_distance": "yes",
        "personality_type": "INTJ",
        "love_language": "acts_of_service",
        "communication_style": "playful",
        "smoking_preference": "never",
        "drinking_preference": "occasionally",
        "pet_preference": "none",
        "exercise_frequency": "daily",
        "hobbies": ["coding", "cooking", "football"],
        "interests": ["technology", "food", "sports"],
        "preferred_gender": "female",
        "age_range_min": 25,
        "age_range_max": 36,
        "max_distance": 150,
        "profile_picture": "https://randomuser.me/api/portraits/men/32.jpg",
    },
    {
        "email": "fatima.bello@bondah.test",
        "name": "Fatima Bello",
        "username": "fatima_bello",
        "gender": "female",
        "date_of_birth": date(1997, 1, 30),
        "city": "Abuja",
        "state": "FCT",
        "country": "Nigeria",
        "bio": "Doctor with a passion for community health. Love reading and quiet evenings.",
        "looking_for": "A God-fearing, emotionally mature man ready for a halal relationship.",
        "religion": "Muslim",
        "religion_importance": "very",
        "genotype": "AA",
        "ethnicity": "black",
        "education_level": "doctorate",
        "job_title": "Medical Doctor",
        "company_name": "National Hospital Abuja",
        "have_kids": "no",
        "want_kids": "maybe",
        "future_kids": "maybe",
        "marriage_plans": "yes",
        "relationship_status": "single",
        "dating_type": "marriage",
        "open_to_long_distance": "no",
        "personality_type": "INFJ",
        "love_language": "words_of_affirmation",
        "communication_style": "reserved",
        "smoking_preference": "never",
        "drinking_preference": "never",
        "pet_preference": "none",
        "exercise_frequency": "2x_week",
        "hobbies": ["reading", "yoga", "volunteering"],
        "interests": ["health", "education", "travel"],
        "preferred_gender": "male",
        "age_range_min": 30,
        "age_range_max": 45,
        "max_distance": 80,
        "profile_picture": "https://randomuser.me/api/portraits/women/68.jpg",
    },
    {
        "email": "david.asante@bondah.test",
        "name": "David Asante",
        "username": "david_asante",
        "gender": "male",
        "date_of_birth": date(1988, 11, 5),
        "city": "Kumasi",
        "state": "Ashanti",
        "country": "Ghana",
        "bio": "Entrepreneur and gym lover. Building businesses and looking to build a family.",
        "looking_for": "A supportive, ambitious woman who values family as much as career.",
        "religion": "Christian",
        "religion_importance": "very",
        "genotype": "AA",
        "ethnicity": "black",
        "education_level": "bachelor",
        "job_title": "CEO",
        "company_name": "Asante Ventures",
        "have_kids": "yes",
        "no_of_kids": 1,
        "want_kids": "yes",
        "future_kids": "yes",
        "marriage_plans": "yes",
        "relationship_status": "divorced",
        "dating_type": "serious",
        "open_to_long_distance": "maybe",
        "personality_type": "ENTJ",
        "love_language": "gifts",
        "communication_style": "direct",
        "smoking_preference": "never",
        "drinking_preference": "occasionally",
        "pet_preference": "dog",
        "exercise_frequency": "5x_week",
        "hobbies": ["gym", "business", "reading"],
        "interests": ["entrepreneurship", "finance", "family"],
        "preferred_gender": "female",
        "age_range_min": 27,
        "age_range_max": 40,
        "max_distance": 200,
        "profile_picture": "https://randomuser.me/api/portraits/men/55.jpg",
    },
    {
        "email": "zara.ibrahim@bondah.test",
        "name": "Zara Ibrahim",
        "username": "zara_ibrahim",
        "gender": "female",
        "date_of_birth": date(1993, 6, 18),
        "city": "Nairobi",
        "state": "Nairobi County",
        "country": "Kenya",
        "bio": "Fashion designer with a love for storytelling and long walks on the beach.",
        "looking_for": "Someone creative, emotionally intelligent, and not afraid of depth.",
        "religion": "Muslim",
        "religion_importance": "somewhat",
        "genotype": "AA",
        "ethnicity": "black",
        "education_level": "bachelor",
        "job_title": "Creative Director",
        "company_name": "Zara Designs Studio",
        "have_kids": "no",
        "want_kids": "yes",
        "future_kids": "yes",
        "marriage_plans": "yes",
        "relationship_status": "single",
        "dating_type": "serious",
        "open_to_long_distance": "yes",
        "personality_type": "ENFP",
        "love_language": "physical_touch",
        "communication_style": "romantic",
        "smoking_preference": "never",
        "drinking_preference": "never",
        "pet_preference": "cat",
        "exercise_frequency": "2x_week",
        "hobbies": ["fashion", "writing", "dancing"],
        "interests": ["art", "culture", "travel"],
        "preferred_gender": "male",
        "age_range_min": 28,
        "age_range_max": 42,
        "max_distance": 300,
        "profile_picture": "https://randomuser.me/api/portraits/women/91.jpg",
    },
]

BONDMAKERS = [
    {
        "email": "grace.okonkwo@bondah.test",
        "name": "Grace Okonkwo",
        "username": "grace_bondmaker",
        "gender": "female",
        "date_of_birth": date(1980, 3, 14),
        "city": "Lagos",
        "state": "Lagos",
        "country": "Nigeria",
        "bio": "Certified relationship coach with 10+ years helping couples find lasting love.",
        "bondmaker_bio": "I specialise in connecting high-achieving professionals who are serious about commitment.",
        "thought_leadership": (
            "Love is not found by chance — it is built with intention. "
            "My approach combines cultural intelligence with emotional compatibility science."
        ),
        "religion": "Christian",
        "ethnicity": "black",
        "education_level": "master",
        "job_title": "Relationship Coach",
        "company_name": "Grace Matchmaking Agency",
        "personality_type": "ENFJ",
        "communication_style": "direct",
        "profile_picture": "https://randomuser.me/api/portraits/women/12.jpg",
        "is_matchmaker": True,
    },
    {
        "email": "samuel.darko@bondah.test",
        "name": "Samuel Darko",
        "username": "samuel_bondmaker",
        "gender": "male",
        "date_of_birth": date(1975, 9, 22),
        "city": "Accra",
        "state": "Greater Accra",
        "country": "Ghana",
        "bio": "Former marriage counsellor turned professional matchmaker. I believe every person deserves love.",
        "bondmaker_bio": "Specialising in diaspora Africans looking to connect with their roots through meaningful relationships.",
        "thought_leadership": (
            "The best matches are rooted in shared values, not just shared interests. "
            "I help clients discover what they truly need, not just what they think they want."
        ),
        "religion": "Christian",
        "ethnicity": "black",
        "education_level": "master",
        "job_title": "Professional Matchmaker",
        "company_name": "Darko Connections",
        "personality_type": "INFJ",
        "communication_style": "romantic",
        "profile_picture": "https://randomuser.me/api/portraits/men/78.jpg",
        "is_matchmaker": True,
    },
    {
        "email": "aisha.musa@bondah.test",
        "name": "Aisha Musa",
        "username": "aisha_bondmaker",
        "gender": "female",
        "date_of_birth": date(1983, 7, 8),
        "city": "Abuja",
        "state": "FCT",
        "country": "Nigeria",
        "bio": "Social psychologist and matchmaker. I use science and empathy to create powerful connections.",
        "bondmaker_bio": "Focused on professional Muslim women and men seeking halal relationships grounded in respect.",
        "thought_leadership": (
            "Compatibility is more than a checklist. "
            "Real connection happens when two people align in purpose, faith, and vision for the future."
        ),
        "religion": "Muslim",
        "ethnicity": "black",
        "education_level": "doctorate",
        "job_title": "Social Psychologist & Matchmaker",
        "company_name": "Musa Halal Connections",
        "personality_type": "INTJ",
        "communication_style": "reserved",
        "profile_picture": "https://randomuser.me/api/portraits/women/33.jpg",
        "is_matchmaker": True,
    },
]


class Command(BaseCommand):
    help = "Seed test accounts for Love Seekers and Bondmakers"

    def handle(self, *args, **options):
        self.stdout.write(self.style.MIGRATE_HEADING("Seeding test accounts..."))

        created_count = 0
        skipped_count = 0

        for data in SEEKERS + BONDMAKERS:
            defaults = {
                "username": data["username"],
                "name": data["name"],
                "gender": data.get("gender"),
                "date_of_birth": data.get("date_of_birth"),
                "city": data.get("city"),
                "state": data.get("state"),
                "country": data.get("country"),
                "bio": data.get("bio", ""),
                "bondmaker_bio": data.get("bondmaker_bio", ""),
                "thought_leadership": data.get("thought_leadership", ""),
                "looking_for": data.get("looking_for", ""),
                "religion": data.get("religion"),
                "religion_importance": data.get("religion_importance"),
                "genotype": data.get("genotype"),
                "ethnicity": data.get("ethnicity"),
                "education_level": data.get("education_level"),
                "job_title": data.get("job_title"),
                "company_name": data.get("company_name"),
                "have_kids": data.get("have_kids"),
                "no_of_kids": data.get("no_of_kids"),
                "want_kids": data.get("want_kids"),
                "future_kids": data.get("future_kids"),
                "marriage_plans": data.get("marriage_plans"),
                "relationship_status": data.get("relationship_status"),
                "dating_type": data.get("dating_type"),
                "open_to_long_distance": data.get("open_to_long_distance"),
                "personality_type": data.get("personality_type"),
                "love_language": data.get("love_language"),
                "communication_style": data.get("communication_style"),
                "smoking_preference": data.get("smoking_preference"),
                "drinking_preference": data.get("drinking_preference"),
                "pet_preference": data.get("pet_preference"),
                "exercise_frequency": data.get("exercise_frequency"),
                "hobbies": data.get("hobbies", []),
                "interests": data.get("interests", []),
                "preferred_gender": data.get("preferred_gender"),
                "age_range_min": data.get("age_range_min", 18),
                "age_range_max": data.get("age_range_max", 100),
                "max_distance": data.get("max_distance", 50),
                "profile_picture": data.get("profile_picture"),
                "is_matchmaker": data.get("is_matchmaker", False),
                "is_active": True,
            }

            # Strip keys with None values to avoid overwriting model defaults
            defaults = {k: v for k, v in defaults.items() if v is not None}

            user, created = User.objects.get_or_create(
                email=data["email"],
                defaults=defaults,
            )

            if created:
                user.set_password(TEST_PASSWORD)
                user.save(update_fields=["password"])
                role = "Bondmaker" if user.is_matchmaker else "Love Seeker"
                self.stdout.write(
                    self.style.SUCCESS(f"  ✓ Created {role}: {user.email}")
                )
                created_count += 1
            else:
                self.stdout.write(
                    self.style.WARNING(f"  ~ Skipped (exists): {user.email}")
                )
                skipped_count += 1

        self.stdout.write("")
        self.stdout.write(
            self.style.SUCCESS(
                f"Done. {created_count} created, {skipped_count} skipped."
            )
        )
        self.stdout.write(
            self.style.MIGRATE_HEADING(f"Password for all accounts: {TEST_PASSWORD}")
        )
