# Generated by Django 4.2.7 on 2026-01-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puzzleverification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Puzzle Verification",
                "verbose_name_plural": "Puzzle Verifications",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="puzzleverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
