# Generated by Django 4.2.7 on 2026-01-29 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_alter_puzzleverification_options_user_last_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="availability_status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userroleselection",
            name="selected_role",
            field=models.CharField(
                choices=[
                    ("looking_for_love", "Looking for Love"),
                    ("bondmaker", "Bondmaker"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SuggestedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bondmaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_for",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("bondmaker", "user", "suggested_user")},
            },
        ),
        migrations.CreateModel(
            name="BondmakerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "bondmaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribed_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bondmaker_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("bondmaker", "user")},
            },
        ),
    ]
