# Generated by Django 4.2.7 on 2026-02-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0004_bondcoinwallet_visibility_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usermatch",
            unique_together={("user1", "user2")},
        ),
    ]
