# Generated by Django 4.2.7 on 2026-02-04 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0006_alter_usermatch_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_balance", models.IntegerField(default=0)),
                ("locked_balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[("credit", "credit"), ("debit", "debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="bondcointransaction",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="bondcointransaction",
            name="package",
        ),
        migrations.RemoveField(
            model_name="bondcointransaction",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="bondcointransaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bondcoinwallet",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="bondcoinpackage",
            name="dating_bond_is_acti_0bfa3a_idx",
        ),
        migrations.AlterField(
            model_name="bondcoinpackage",
            name="bondcoin_amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="bondcoinpackage",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bondcoinpackage",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bondcoinpackage",
            name="price_usd",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="BondcoinWallet",
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_ledger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gifttransaction",
            name="bondcoin_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dating.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="livegift",
            name="bondcoin_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dating.wallettransaction",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="bondcoin_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_transactions",
                to="dating.wallettransaction",
            ),
        ),
        migrations.DeleteModel(
            name="BondcoinTransaction",
        ),
    ]
