# Generated by Django 4.2.7 on 2026-02-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0014_report"),
    ]

    operations = []
