# Generated by Django 4.2.7 on 2026-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0015_rename_kids_plans_user_future_kids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of general interests",
                null=True,
            ),
        ),
    ]
