# Generated by Django 4.2.7 on 2026-02-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0016_alter_user_interests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
