# Generated by Django 4.2.7 on 2026-02-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0015_seed_traits"),
        ("dating", "0017_remove_user_age_user_date_of_birth"),
    ]

    operations = []
