# Generated by Django 4.2.7 on 2026-02-12 10:05

from django.db import connection, migrations, models


def add_reset_token_field_if_not_exists(apps, schema_editor):
    """Add reset_token UUID column to PasswordResetOTP if it doesn't exist.

    Uses Django's database introspection API to check for column existence,
    ensuring compatibility with both SQLite (local) and PostgreSQL (production).
    """
    table_name = "dating_passwordresetotp"
    column_name = "reset_token"

    with connection.cursor() as cursor:
        columns = [
            col.name
            for col in connection.introspection.get_table_description(
                cursor, table_name
            )
        ]
        exists = column_name in columns

    if not exists:
        with connection.cursor() as cursor:
            cursor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN {column_name} uuid NULL"
            )


class Migration(migrations.Migration):
    """Add reset_token field to PasswordResetOTP model."""

    dependencies = [
        ("dating", "0018_merge_20260212_0926"),
    ]

    operations = [
        migrations.RunPython(
            add_reset_token_field_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
