# Generated by Django 4.2.7 on 2026-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0024_alter_matchrequest_bondmaker_earning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibility",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")], max_length=20
            ),
        ),
    ]
