# Generated by Django 4.2.7 on 2026-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0025_alter_visibility_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dating_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casual", "Casual Dating"),
                    ("serious", "Serious Relationship"),
                    ("marriage", "Marriage"),
                    ("sugar", "Sugar Relationship"),
                    ("friendship", "Friendship"),
                    ("short_term", "Short Term"),
                    ("not_sure_yet", "Not Sure Yet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
