# Generated by Django 4.2.7 on 2026-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0027_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="visibility",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CoinTransaction",
        ),
    ]
