# Generated by Django 4.2.7 on 2026-02-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0030_bondmakertaskcompletion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRevenueRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("match_request", "Match Request"),
                            ("private_visibility", "Private Visibility"),
                        ],
                        max_length=50,
                    ),
                ),
                ("coins_used", models.IntegerField()),
                (
                    "real_revenue_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "platform_share_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "bondmaker_share_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bondmaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MatchRevenueSplit",
        ),
        migrations.AddIndex(
            model_name="productrevenuerecord",
            index=models.Index(
                fields=["bondmaker", "paid"], name="dating_prod_bondmak_2b858a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrevenuerecord",
            index=models.Index(
                fields=["product_type"], name="dating_prod_product_775ae1_idx"
            ),
        ),
    ]
