# Generated by Django 5.2.11 on 2026-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dating",
            "0033_storyinteraction_alter_storyreaction_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bondcoin_balance",
        ),
        migrations.DeleteModel(
            name="BondmakerWallet",
        ),
    ]
