# Generated by Django 5.2.11 on 2026-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0034_remove_user_bondcoin_balance_delete_bondmakerwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dating_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("serious", "Serious Relationship"),
                    ("marriage", "Marriage"),
                    ("sugar", "Sugar Relationship"),
                    ("friendship", "Friendship"),
                    ("short_term", "Short Term"),
                    ("not_sure_yet", "Not Sure Yet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
