# Generated by Django 5.2.11 on 2026-03-16 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0035_alter_user_dating_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("moderator", "Moderator"),
                            ("finance", "Finance"),
                            ("analytics", "Analytics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("can_view_overview", models.BooleanField(default=True)),
                ("can_view_applications", models.BooleanField(default=False)),
                ("can_view_withdrawals", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_manage_team", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_principal_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AdminPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_overview", models.BooleanField(default=True)),
                ("can_view_applications", models.BooleanField(default=False)),
                ("can_view_withdrawals", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_manage_team", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dating.adminrole",
            ),
        ),
        migrations.DeleteModel(
            name="AdminOTP",
        ),
        migrations.DeleteModel(
            name="AdminUser",
        ),
    ]
