# Generated by Django 5.2.11 on 2026-04-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0039_selfieverification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deviceregistration",
            unique_together={("user", "device_id")},
        ),
    ]
