# Generated by Django 5.2.11 on 2026-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0041_auto_20260403_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bondmaker_cover_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bondmaker_profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
