# Generated by Django 5.2.11 on 2026-04-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0042_user_bondmaker_cover_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bondamker_bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
