# Generated by Django 5.2.11 on 2026-04-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0043_user_bondamker_bio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="bondamker_bio",
            new_name="bondmaker_bio",
        ),
    ]
