# Generated by Django 5.2.11 on 2026-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0044_rename_bondamker_bio_user_bondmaker_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialisation",
            name="category",
            field=models.CharField(
                choices=[
                    ("casual", "Casual Dating"),
                    ("lgbtq", "LGBTQ+"),
                    ("lavender", "Lavender Marriage"),
                    ("sugar", "Sugar Relationship"),
                    ("marriage", "Marriage-Oriented"),
                    ("companionship", "Companionship"),
                    ("cultural", "Cultural Matching"),
                    ("elite", "Elite Only Matching"),
                    ("widow", "Widow/Widower Matchmaking"),
                    ("divorced", "Divorced/Single Parent Matching"),
                    ("career", "Career Focused Matching"),
                    ("arabs", "Arabs/Khaṭṭābah Matching"),
                    ("hindi", "Hindi/Punjabi Matching"),
                    ("christian", "Christian Matching"),
                    ("islam", "Islam Matching"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
    ]
