# Generated by Django 5.2.11 on 2026-04-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0045_alter_specialisation_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bonds_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="shares_count",
        ),
    ]
