# Generated by Django 5.2.11 on 2026-04-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0047_remove_post_dating_post_post_ty_80be04_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentverification",
            name="experience_years",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
