# Generated by Django 5.2.11 on 2026-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0050_remove_documentverification_experience_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceregistration",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("fcm", "Firebase Cloud Messaging"),
                    ("expo", "Expo Push Notifications"),
                ],
                default="expo",
                max_length=5,
            ),
        ),
    ]
