# Generated by Django 5.2.11 on 2026-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0052_add_can_approve_applications_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_flagged_for_deletion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="scheduled_deletion_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Bondah Pro")],
                default="free",
                max_length=50,
                unique=True,
            ),
        ),
    ]
