# Generated by Django 5.2.11 on 2026-06-22 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0053_user_is_flagged_for_deletion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_for",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("restricted", "Restricted"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
