# Generated by Django 5.2.11 on 2026-07-18 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0056_user_notify_on_bondmaker_update_user_notify_on_like_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("profile_viewed", "Profile View"),
                            ("match_made", "Match Made"),
                            ("match_accepted", "Match Accepted"),
                            ("match_rejected", "Match Rejected"),
                            ("match_cancelled", "Match Cancelled"),
                            ("match_expired", "Match Expired"),
                            ("match_updated", "Match Updated"),
                            ("match_deleted", "Match Deleted"),
                            ("gift_sent", "Gift Sent"),
                            ("post_like", "Post Liked"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="idx_recipient_created_at",
                    )
                ],
            },
        ),
    ]
