# Generated by Django 5.2.11 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0057_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminrole",
            name="can_approve_applications",
            field=models.BooleanField(default=False),
        ),
    ]
