# Generated by Django 5.2.11 on 2026-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0058_add_can_approve_applications_to_adminrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("password_reset", "Password Reset"),
                    ("login_info_change", "Login Info Change"),
                ],
                default="password_reset",
                max_length=30,
            ),
        ),
    ]
