# Generated by Django 5.2.11 on 2026-10-03 12:14

import ast

import dating.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _to_url_list(value):
    """
    Old rows hold either one URL or the text of a Python list, because the
    serializer saved lists into a single-URL column ("['https://...']").
    """
    if not value:
        return []
    value = value.strip()
    if value.startswith("["):
        try:
            parsed = ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return []
        return [str(item) for item in parsed if isinstance(item, str) and item]
    return [value]


def copy_post_video_lists(apps, schema_editor):
    Post = apps.get_model("dating", "Post")
    batch = []
    for post in Post.objects.exclude(video_url__isnull=True, video_thumbnail__isnull=True).iterator():
        post.video_url_list = _to_url_list(post.video_url)
        post.video_thumbnail_list = _to_url_list(post.video_thumbnail)
        batch.append(post)
        if len(batch) >= 500:
            Post.objects.bulk_update(batch, ["video_url_list", "video_thumbnail_list"])
            batch = []
    if batch:
        Post.objects.bulk_update(batch, ["video_url_list", "video_thumbnail_list"])


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0063_backfill_chat_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_thumbnail_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Video poster frame (r2:// reference)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='back_image_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Back image of document', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='front_image_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Front image of document', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Image (r2:// reference)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Video (r2:// reference)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_note_url',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Voice note audio (r2:// reference)', max_length=500, null=True),
        ),
        # Post video columns become lists (the API always sent lists). Postgres
        # cannot cast arbitrary text to JSON, so copy into new columns, convert,
        # then swap them in under the original names.
        migrations.AddField(
            model_name='post',
            name='video_url_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_post_video_lists, migrations.RunPython.noop),
        migrations.RemoveField(model_name='post', name='video_url'),
        migrations.RemoveField(model_name='post', name='video_thumbnail'),
        migrations.RenameField(model_name='post', old_name='video_url_list', new_name='video_url'),
        migrations.RenameField(
            model_name='post', old_name='video_thumbnail_list', new_name='video_thumbnail'
        ),
        migrations.AlterField(
            model_name='post',
            name='video_thumbnail',
            field=models.JSONField(blank=True, default=list, help_text='List of video thumbnail references'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.JSONField(blank=True, default=list, help_text='List of video references'),
        ),
        migrations.AlterField(
            model_name='selfieverification',
            name='selfie_image_url',
            field=dating.models.fields.MediaRefField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bondmaker_cover_picture',
            field=dating.models.fields.MediaRefField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bondmaker_profile_picture',
            field=dating.models.fields.MediaRefField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=dating.models.fields.MediaRefField(blank=True, help_text='Main profile picture (r2:// reference or legacy URL)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=40)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('declared_size', models.PositiveBigIntegerField()),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for upload'), ('ready', 'Verified'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('purged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to='dating.chat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='dating_medi_status_1512c4_idx'), models.Index(fields=['owner', 'status'], name='dating_medi_owner_i_486969_idx'), models.Index(fields=['status', 'purged'], name='dating_medi_status_ae3be8_idx')],
            },
        ),
    ]
