# Generated by Django 5.2.11 on 2026-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0064_r2_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='cleared_before_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
