# Generated by Django 5.2.11 on 2026-10-06 20:39

import django.core.validators
from django.db import migrations, models


def refuse_negative_balances(apps, schema_editor):
    """Stop the deploy loudly rather than let the new constraints fail midway.

    Negative balances are real money errors; they need a human to correct them.
    """
    Wallet = apps.get_model("dating", "Wallet")
    bad = list(
        Wallet.objects.filter(
            models.Q(available_balance__lt=0) | models.Q(locked_balance__lt=0)
        ).values_list("id", "user_id", "available_balance", "locked_balance")[:50]
    )
    if bad:
        raise RuntimeError(
            "Wallets with negative balances must be corrected before migrating "
            f"(id, user_id, available, locked): {bad}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0065_chat_clear_cursor'),
    ]

    operations = [
        migrations.RunPython(refuse_negative_balances, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_conversion_percent', models.PositiveSmallIntegerField(default=70, help_text="Share of a gift's coin cost the recipient gets when converting it to coins.", validators=[django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gifttransaction',
            name='converted_coins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='dating_wall_user_id_e25ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_available_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='wallet_locked_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='platformsettings',
            constraint=models.CheckConstraint(condition=models.Q(('gift_conversion_percent__lte', 100)), name='platform_gift_conversion_percent_max_100'),
        ),
    ]
