# Generated by Django 5.2.11 on 2026-10-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0066_wallet_ledger_gifts_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('app_user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='matchrequest',
            name='dating_matc_status_cfac84_idx',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='hold_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dating.wallettransaction'),
        ),
        migrations.AddField(
            model_name='visibility',
            name='hold_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dating.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='coin_debt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='refund_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('matched', 'Matched'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['status', 'created_at'], name='dating_matc_status_8ba5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecatevent',
            index=models.Index(fields=['status', 'received_at'], name='dating_reve_status_c0d2a9_idx'),
        ),
    ]
