# Generated by Django 5.2.11 on 2026-10-07 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0069_adopt_legacy_holds'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySwipeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_usd']},
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='dating_user_user_id_19e214_idx',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_issue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_event_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='store',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(help_text="Display name like 'Bondah Pro'", max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='live_hours_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Bondah Pro'), ('prime', 'Bondah Prime')], db_index=True, default='free', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_bondcoins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text="Reference price in USD; the app shows the store's price", max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('matched', 'Matched'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(default='store', help_text='apple, google', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dating.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', 'end_date'], name='dating_user_user_id_2edb65_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('original_transaction_id__isnull', False)), fields=('store', 'original_transaction_id'), name='unique_store_subscription'),
        ),
        migrations.AddField(
            model_name='dailyswipecount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailyswipecount',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='unique_daily_swipe_count'),
        ),
    ]
