# Generated by Django 5.2.11 on 2026-10-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0071_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='visibility',
            name='expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visibility',
            name='renewal_hold_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dating.wallettransaction'),
        ),
        migrations.AddField(
            model_name='visibility',
            name='renewal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visibility',
            name='renewal_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='visibility',
            index=models.Index(fields=['bondmaker', 'renewal_status'], name='dating_visi_bondmak_202a97_idx'),
        ),
        migrations.AddIndex(
            model_name='visibility',
            index=models.Index(fields=['status', 'expires_at'], name='dating_visi_status_d9c414_idx'),
        ),
    ]
