# Generated by Django 5.2.11 on 2026-10-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0072_visibility_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedmatch',
            name='charge_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dating.wallettransaction'),
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dating.chat'),
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='liked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('liked', 'Liked'), ('passed', 'Passed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='suggestedmatch',
            index=models.Index(fields=['user', 'status', '-created_at'], name='dating_sugg_user_id_fb6c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedmatch',
            index=models.Index(fields=['suggested_user', 'status', '-liked_at'], name='dating_sugg_suggest_5b366e_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedmatch',
            index=models.Index(fields=['status', 'liked_at'], name='dating_sugg_status_8056b0_idx'),
        ),
    ]
