# Generated by Django 5.2.11 on 2026-10-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0073_suggestion_lifecycle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='suggestedmatch',
            name='dating_sugg_suggest_5b366e_idx',
        ),
        migrations.RemoveIndex(
            model_name='suggestedmatch',
            name='dating_sugg_status_8056b0_idx',
        ),
        migrations.RemoveField(
            model_name='suggestedmatch',
            name='charge_transaction',
        ),
        migrations.RemoveField(
            model_name='suggestedmatch',
            name='chat',
        ),
        migrations.AddField(
            model_name='suggestedmatch',
            name='match_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion', to='dating.matchrequest'),
        ),
        migrations.AlterField(
            model_name='suggestedmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('liked', 'Liked'), ('passed', 'Passed')], default='pending', max_length=10),
        ),
    ]
