# Generated by Django 5.2.11 on 2026-10-08 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_old_resolved_reports(apps, schema_editor):
    Report = apps.get_model("dating", "Report")
    Report.objects.filter(resolved=True).update(status="resolved")



class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0074_suggestion_via_match_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=100)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('tier', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('restricted', 'Restricted'), ('suspended', 'Suspended')], db_index=True, default='good', max_length=10)),
                ('active_strikes', models.PositiveSmallIntegerField(default=0)),
                ('suspended_by_admin', models.BooleanField(default=False)),
                ('suspension_note', models.CharField(blank=True, default='', max_length=500)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('low_score', 'Accepted a low-score match'), ('automation', 'Automated-looking activity')], max_length=12)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Reason accepted'), ('rejected', 'Reason rejected')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('report', 'Upheld report'), ('expired_requests', 'Too many expired requests'), ('automation', 'Automated-looking activity'), ('low_score', 'Unjustified low-score matches'), ('manual', 'Added by Team Bondah')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['bondmaker', 'decided_at'], name='dating_matc_bondmak_068271_idx'),
        ),
        migrations.AddField(
            model_name='accounthealth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_health', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthflag',
            name='match_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dating.matchrequest'),
        ),
        migrations.AddField(
            model_name='healthflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strike',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strike',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accounthealth',
            index=models.Index(fields=['tier', 'score'], name='dating_acco_tier_5824a0_idx'),
        ),
        migrations.AddIndex(
            model_name='healthflag',
            index=models.Index(fields=['status', '-created_at'], name='dating_heal_status_aeb115_idx'),
        ),
        migrations.AddIndex(
            model_name='healthflag',
            index=models.Index(fields=['user', 'kind', 'status', 'reviewed_at'], name='dating_heal_user_id_4736ca_idx'),
        ),
        migrations.AddIndex(
            model_name='strike',
            index=models.Index(fields=['user', 'expires_at'], name='dating_stri_user_id_c4d259_idx'),
        ),
        migrations.AddIndex(
            model_name='strike',
            index=models.Index(fields=['user', 'reason', 'created_at'], name='dating_stri_user_id_85a924_idx'),
        ),
        migrations.RunPython(mark_old_resolved_reports, migrations.RunPython.noop),
    ]
