# Generated by Django 5.2.11 on 2026-10-08 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0075_account_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='coin_cash_rate_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='US dollars paid out per earned coin.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_withdrawal_coins',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest withdrawal, in coins.', null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='withdrawal_fee_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taken from each withdrawal's cash amount.", max_digits=8),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('stablecoin', 'Stablecoin'), ('manual', 'Bank or mobile money')], max_length=12)),
                ('destination', models.JSONField(default=dict)),
                ('coins', models.PositiveIntegerField()),
                ('rate_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payout_reference', models.CharField(blank=True, default='', max_length=200)),
                ('admin_note', models.CharField(blank=True, default='', max_length=500)),
                ('health_tier', models.CharField(blank=True, default='', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hold_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dating.wallettransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='dating_with_status_c41537_idx'), models.Index(fields=['user', '-created_at'], name='dating_with_user_id_ac1b5e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('coins__gt', 0)), name='withdrawal_coins_positive')],
            },
        ),
    ]
