# Generated by Django 5.2.11 on 2026-10-08 22:55

from django.db import migrations, models


def map_audiences(apps, schema_editor):
    # Old values: public, friends (followers), private. "followers" was sent by
    # the app but never valid. Narrow audiences become followers-only.
    Post = apps.get_model("dating", "Post")
    Post.objects.filter(visibility="public").update(visibility="everyone")
    Post.objects.exclude(visibility__in=["everyone", "seekers", "followers"]).update(visibility="followers")



class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0076_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('seekers', 'Love seekers only'), ('followers', 'My followers only')], default='everyone', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', 'visibility', '-created_at'], name='dating_post_is_acti_d0f06f_idx'),
        ),
        migrations.RunPython(map_audiences, migrations.RunPython.noop),
    ]
