# Generated by Django 5.2.11 on 2026-10-08 23:13

from django.db import migrations, models


def clear_follow_end_dates(apps, schema_editor):
    # Follows were given a 30-day end date as if paid; they last until unfollowed.
    Follow = apps.get_model("dating", "BondmakerSubscription")
    Follow.objects.filter(active=True).update(end_date=None)



class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0077_post_audiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmakersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(clear_follow_end_dates, migrations.RunPython.noop),
    ]
