# Generated by Django 5.2.11 on 2026-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0078_follows_do_not_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('profile_viewed', 'Profile View'), ('match_made', 'Match Made'), ('match_accepted', 'Match Accepted'), ('match_rejected', 'Match Rejected'), ('match_cancelled', 'Match Cancelled'), ('match_expired', 'Match Expired'), ('match_updated', 'Match Updated'), ('match_deleted', 'Match Deleted'), ('gift_sent', 'Gift Sent'), ('post_like', 'Post Liked'), ('post_comment', 'Post Comment'), ('comment_like', 'Comment Liked')], max_length=50),
        ),
    ]
