# Generated by Django 5.2.11 on 2026-10-09 16:12

from django.db import migrations, models


def only_supported_languages(apps, schema_editor):
    """The app ships English and Arabic only; anything else (en-GB, fr, ...) becomes English."""
    User = apps.get_model("dating", "User")
    User.objects.filter(preferred_language__istartswith="ar").exclude(preferred_language="ar").update(preferred_language="ar")
    User.objects.exclude(preferred_language__in=("en", "ar")).update(preferred_language="en")


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0079_bond_story_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text="User's preferred app language", max_length=10),
        ),
        migrations.RunPython(only_supported_languages, migrations.RunPython.noop),
    ]
