# Generated by Django 5.2.11 on 2026-10-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0080_account_deletion_and_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='bondmaker_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='status_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='AccountStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dating_acco_user_id_d58112_idx')],
            },
        ),
        migrations.CreateModel(
            name='BondmakerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, default='', max_length=1000)),
                ('reapply_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='dating.documentverification')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('selfie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='dating.selfieverification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondmaker_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='dating_bond_status_e10885_idx'), models.Index(fields=['user', '-submitted_at'], name='dating_bond_user_id_aadb27_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'changes_requested'))), fields=('user',), name='one_open_bondmaker_application')],
            },
        ),
    ]
