from django.urls import path
from .views import (
    UserCreateView, 
    NewsletterSignupView, 
    GetPuzzleView, 
    SubmitPuzzleAnswerView, 
    EarnCoinsView, 
    SpendCoinsView,
    JoinWaitlistView,
    SendNewsletterWelcomeEmailView,
    SendWaitlistConfirmationEmailView,
    SendGenericEmailView,
    JobListView,
    JobDetailView,
    JobApplicationView,
    JobOptionsView,
    AdminLoginView,
    AdminOTPVerificationView,
    AdminJobListView,
    AdminJobCreateView,
    AdminJobUpdateView,
    AdminJobApplicationsView,
    AdminJobApplicationDetailView,
    AdminUpdateApplicationStatusView,
    AdminWaitlistListView,
    AdminNewsletterListView,
    AdminTokenRefreshView,
    AdminLogoutView,
    AdminVerifyTokenView,
    AdminDebugAuthView,
    TranslationView,
    SupportedLanguagesView,
    TranslationHistoryView,
    TranslationStatsView,
    # Mobile App Authentication Views
    UserRegisterView,
    UserLoginView,
    UserLogoutView,
    TokenRefreshView,
    PasswordResetView,
    PasswordResetConfirmView,
    UserProfileView,
    DeviceRegistrationView,
    # OAuth Views
    GoogleOAuthView,
    AppleOAuthView,
    SocialLoginView,
    OAuthLinkAccountView,
    OAuthUnlinkAccountView,
    SocialAccountsListView,
    # Location Management Views
    LocationUpdateView,
    AddressGeocodeView,
    LocationPrivacyUpdateView,
    LocationPermissionsView,
    LocationHistoryView,
    NearbyUsersView,
    MatchPreferencesView,
    UserLocationProfileView,
    LocationStatisticsView,
)

urlpatterns = [
    # Public API endpoints
    path('create-user/', UserCreateView.as_view(), name='create-user'),
    path('newsletter/signup/', NewsletterSignupView.as_view(), name='newsletter-signup'),
    path('newsletter/subscribe/', NewsletterSignupView.as_view(), name='newsletter-subscribe'),
    path('puzzle/', GetPuzzleView.as_view(), name='get-puzzle'),
    path('puzzle/verify/', SubmitPuzzleAnswerView.as_view(), name='verify-puzzle'),
    path('coins/earn/', EarnCoinsView.as_view(), name='earn-coins'),
    path('coins/spend/', SpendCoinsView.as_view(), name='spend-coins'),
    path('waitlist/', JoinWaitlistView.as_view(), name='join-waitlist'),
    path('email/send-newsletter-welcome/', SendNewsletterWelcomeEmailView.as_view(), name='send-newsletter-welcome'),
    path('email/send-waitlist-confirmation/', SendWaitlistConfirmationEmailView.as_view(), name='send-waitlist-confirmation'),
    path('email/send/', SendGenericEmailView.as_view(), name='send-generic-email'),
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('jobs/<int:id>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/apply/', JobApplicationView.as_view(), name='job-application'),
    path('jobs/options/', JobOptionsView.as_view(), name='job-options'),
    
    # Translation API endpoints
    path('translate/', TranslationView.as_view(), name='translate'),
    path('translate/languages/', SupportedLanguagesView.as_view(), name='supported-languages'),
    path('translate/history/', TranslationHistoryView.as_view(), name='translation-history'),
    path('translate/stats/', TranslationStatsView.as_view(), name='translation-stats'),
    
    # Admin API endpoints
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/verify-otp/', AdminOTPVerificationView.as_view(), name='admin-verify-otp'),
    path('admin/refresh-token/', AdminTokenRefreshView.as_view(), name='admin-refresh-token'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('admin/verify-token/', AdminVerifyTokenView.as_view(), name='admin-verify-token'),
    path('admin/debug-auth/', AdminDebugAuthView.as_view(), name='admin-debug-auth'),
    path('admin/jobs/', AdminJobListView.as_view(), name='admin-job-list'),
    path('admin/jobs/create/', AdminJobCreateView.as_view(), name='admin-job-create'),
    path('admin/jobs/<int:job_id>/update/', AdminJobUpdateView.as_view(), name='admin-job-update'),
    path('admin/applications/', AdminJobApplicationsView.as_view(), name='admin-applications'),
    path('admin/applications/<int:application_id>/', AdminJobApplicationDetailView.as_view(), name='admin-application-detail'),
    path('admin/applications/<int:application_id>/status/', AdminUpdateApplicationStatusView.as_view(), name='admin-update-application-status'),
    path('admin/waitlist/', AdminWaitlistListView.as_view(), name='admin-waitlist-list'),
    path('admin/newsletter/', AdminNewsletterListView.as_view(), name='admin-newsletter-list'),
    
    # Mobile App Authentication Endpoints
    path('auth/register/', UserRegisterView.as_view(), name='user-register'),
    path('auth/login/', UserLoginView.as_view(), name='user-login'),
    path('auth/logout/', UserLogoutView.as_view(), name='user-logout'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('auth/password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('auth/password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('auth/profile/', UserProfileView.as_view(), name='user-profile'),
    path('auth/device-register/', DeviceRegistrationView.as_view(), name='device-register'),
    
    # OAuth Authentication Endpoints
    path('oauth/google/', GoogleOAuthView.as_view(), name='google-oauth'),
    path('oauth/apple/', AppleOAuthView.as_view(), name='apple-oauth'),
    path('oauth/social-login/', SocialLoginView.as_view(), name='social-login'),
    path('oauth/link-account/', OAuthLinkAccountView.as_view(), name='oauth-link-account'),
    path('oauth/unlink-account/<str:provider>/', OAuthUnlinkAccountView.as_view(), name='oauth-unlink-account'),
    path('oauth/social-accounts/', SocialAccountsListView.as_view(), name='social-accounts-list'),
    
    # Location Management Endpoints
    path('location/update/', LocationUpdateView.as_view(), name='location-update'),
    path('location/geocode/', AddressGeocodeView.as_view(), name='address-geocode'),
    path('location/privacy/', LocationPrivacyUpdateView.as_view(), name='location-privacy'),
    path('location/permissions/', LocationPermissionsView.as_view(), name='location-permissions'),
    path('location/history/', LocationHistoryView.as_view(), name='location-history'),
    path('location/nearby-users/', NearbyUsersView.as_view(), name='nearby-users'),
    path('location/match-preferences/', MatchPreferencesView.as_view(), name='match-preferences'),
    path('location/profile/', UserLocationProfileView.as_view(), name='user-location-profile'),
    path('location/statistics/', LocationStatisticsView.as_view(), name='location-statistics'),
]