DEFAULT_PERIOD_DAYS = 30
CACHE_TIMEOUT_SECONDS = 60 * 5  # 5 minutes
MATCH_STATUS_ACCEPTED = "accepted"
VISIBILITY_PUBLIC = "public"
VISIBILITY_APPROVED = "approved"
INTERACTION_LIKE = "like"
MATCHES_PER_LEVEL = 50
NEXT_BADGE_LEVEL = 10
